<?php

namespace ContainerQjTOVJH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NugJTxDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NugJTxD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NugJTxD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'unite' => ['privates', '.errored..service_locator.NugJTxD.App\\Entity\\Unite', NULL, 'Cannot autowire service ".service_locator.NugJTxD": it references class "App\\Entity\\Unite" but no such service exists.'],
            'validator' => ['services', '.container.private.validator', 'get_Container_Private_ValidatorService', false],
        ], [
            'entityManager' => '?',
            'unite' => 'App\\Entity\\Unite',
            'validator' => '?',
        ]);
    }
}
