<?php

namespace ContainerQjTOVJH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MEfRNNEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mEfRNNE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mEfRNNE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'unite' => ['privates', '.errored..service_locator.mEfRNNE.App\\Entity\\Unite', NULL, 'Cannot autowire service ".service_locator.mEfRNNE": it references class "App\\Entity\\Unite" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'unite' => 'App\\Entity\\Unite',
        ]);
    }
}
