<?php

namespace ContainerQjTOVJH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCour2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.BM1Gbfy.App\Entity\Cour' shared service.
     *
     * @return \App\Entity\Cour
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.BM1Gbfy": it references class "App\\Entity\\Cour" but no such service exists.');
    }
}
