<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXeYL75L\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXeYL75L/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXeYL75L.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXeYL75L\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXeYL75L\App_KernelDevDebugContainer([
    'container.build_hash' => 'XeYL75L',
    'container.build_id' => 'c685bc95',
    'container.build_time' => 1715197199,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXeYL75L');
