<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJy49Ha8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJy49Ha8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJy49Ha8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJy49Ha8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJy49Ha8\App_KernelDevDebugContainer([
    'container.build_hash' => 'Jy49Ha8',
    'container.build_id' => '0562dd51',
    'container.build_time' => 1715213590,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJy49Ha8');
